### ISSUE TITLE
How to visualize the gamut of my own images?

### ISSUE THREAD

**Issue by hminle** [colour-science/colour-analysis-three.js#5]
Hi,

I managed to open the analysis, but cannot upload my own image to analyze, what should I do?

Thanks

**Comment by thomasmansencal** [comment]
Hi @hminle,

No, there is no way to upload your own images, you would need to launch the container locally for that!
The [README](https://github.com/colour-science/colour-analysis-three.js/blob/develop/README.rst) has an example of how to do that.

Cheers,

Thomas

**Comment by hminle** [comment]
> Hi @hminle,
> 
> No, there is no way to upload your own images, you would need to launch the container locally for that!
> The [README](https://github.com/colour-science/colour-analysis-three.js/blob/develop/README.rst) has an example of how to do that.
> 
> Cheers,
> 
> Thomas

Hi @KelSolaar ,
What do you mean by launch the container locally? I launch the container inside my Mac, I open it locally.
But the tool only analyzes existing images. 

Thanks,

**Comment by thomasmansencal** [comment]
Right so if you are already, you should be able to do that:

```shell
$ docker run -d \
--name=colour-analysis \
-e COLOUR_ANALYSIS_JS=https://gitcdn.link/repo/colour-science/colour-analysis-three.js/master/dist/colour-analysis.js \
-e COLOUR_ANALYSIS_POSITION_DTYPE=Float16 \
-e COLOUR_ANALYSIS_COLOUR_DTYPE=Float16 \
-v $IMAGES_DIRECTORY:/home/colour-analysis/static/images \
-p 8020:5000 colourscience/colour-analysis
```

Specifically: `-v $IMAGES_DIRECTORY:/home/colour-analysis/static/images`

Where `$IMAGES_DIRECTORY` is the directory where the images you want to use are located.

**Comment by hminle** [comment]
Hi @KelSolaar 

Thank you.
I got it now

**Comment by hminle** [comment]
Hi @KelSolaar ,
Btw, do you have documents of this tool? 
I want to know all those things like Primary colour space, Secondary colour space,...
All the settings
But I could not find documents about them.

Thanks

**Comment by thomasmansencal** [comment]
There is, unfortunately, no documentation besides what is in the docstrings in the [colour_analysis](https://github.com/colour-science/colour-analysis-three.js/blob/develop/colour_analysis.py) module.

This project was meant to complement the update of https://cinematiccolor.org/ that some of us was working and not directly meant for direct consumption.

I'm meant to do an update though to integrate the code from the new `colour.geometry` sub-package: https://github.com/colour-science/colour/tree/develop/colour/geometry and fix some issues with the latest Three.js versions.

**Comment by hminle** [comment]
Hi @KelSolaar 
So I want to draw out my ProPhoto RGB image gamut to see how much my image could spread over the ProPhoto RGB colour gamut
![image](https://user-images.githubusercontent.com/16201681/79625522-ac0c8300-80f7-11ea-87e6-9f0489234e12.png)

My settings here are okay.
It seems that my ProPhoto RGB image could not spread over 100% ProPhoto RGB gamut region.

![image](https://user-images.githubusercontent.com/16201681/79625588-f8f05980-80f7-11ea-9364-3c81ade61ffe.png)
